### ISSUE TITLE
Add a section for Books

### ISSUE THREAD

**Issue by adds68** [TaptuIT/awesome-devsecops#31]
I think it would be nice to add a section for books related to AppSec/DevSecOps, for example I have found https://www.wiley.com/en-gb/Alice+and+Bob+Learn+Application+Security-p-9781119687405 to be an excellent introduction.

We could maybe mark them as "paid" resources or something?

**Comment by JakobTheDev** [comment]
A books section sounds great, feel free to add a Books section under the Resources heading and include the book you suggested.

We've considered calling out paid vs free resources, though that can be more difficult when there are freemium or other paid models. Leave it unmarked for now, we'll re-evaluate marking paid resources later.
