### ISSUE TITLE
this is really helpful and useful - thanks! any plans to update?

### ISSUE THREAD

**Issue by nathanawmk** [TaptuIT/awesome-devsecops#49]
this is really helpful and useful - thanks! any plans to update?

**Comment by JakobTheDev** [comment]
Glad to hear, thanks for the feedback!

Absolutely, I've been swamped at work of late, but I have a bunch of new tools and resources that I've been using lately that I plan to add to the list soon, once things slow down a little.

Thanks for your patience <3
